Add Feature: ignore specific tmux buffers
aserowy/tmux.nvim pull request #52
Opened 2021-12-14 22:57 UTC by kevintraver

PR for #51

2021-12-15 04:54 UTC, aserowy commented
ty for the pr. I have commented couple small things.

Kind regards
Alexander

2021-12-15 05:18 UTC, kevintraver commented
Hmmm, Im not sure I see the comments

2021-12-15 05:25 UTC, aserowy requested changes
my fault, i didnt finished the review :D

2021-12-15 05:32 UTC, kevintraver commented on lua/tmux/configuration/options.lua
> +        ignore_buffers = { "tmp" },
Ok makes sense

2021-12-15 17:29 UTC, aserowy commented
yeah, i will look into it tomorrow. No idea why its not copying :D

2021-12-16 05:36 UTC, aserowy commented
I fixed it, BUT the version does not function... vim.tbl_deep_extend has problems with this kind of object structure. :dagger:

I guess we must use an unordered table like

```lua
{
  "buffer_name" = true,
}
```

I have to take a closer look into this one.

2021-12-17 06:02 UTC, aserowy commented
Ok, im unsure if the problem was really vim.tbl_deep_extend or my own fat fingers :dagger: 

I reworked the structure to an unordered list and now it works like a charm!

2021-12-17 06:02 UTC, aserowy approved these changes

2021-12-17 06:02 UTC, merged

2021-12-17 06:04 UTC, aserowy commented
ty for your pr @kevintraver

2021-12-17 06:05 UTC, aserowy commented
closes #51