Add wincmd border wrap around
aserowy/tmux.nvim pull request #8
Opened 2021-06-28 23:02 UTC by jdsutherland

Closes #7 

I noticed this only works if `cycle_navigation = false`. My assumption was that `cycle_navigation` is supposed to make tmux panes wrap, but I find that my tmux panes wrap even if this is set to false, so I'm not sure if I'm misunderstanding what it's supposed to do. If you do want to accept this PR, these changes probably shouldn't depend on `cycle_navigation = false`, so we should get that figured out.

2021-06-29 04:05 UTC, aserowy commented
hmm on my end cycle_navigation works. maybe we haven an issue here. I'll check the pr on my machine later this week, rl is wrestling me the next days  :D
btw. the setting cycle_navigation should prevent this behaviour in nvim as well.

2021-06-29 04:35 UTC, aserowy requested changes
Im starting to belive that we should use global functions. Thus we can inject and use key bindings like C-W t as wrapping functions. This would on the other hand break the current api... Hmm, but it would free us and would open us a lot more capabilities. Or is there a function in lua im not aware of to send keys to nvim within a lua function?

```lua
local function wincmd_next(direction, count)
	local prev_winnr = winnr()
	wincmd(direction, count)
	return winnr() ~= prev_winnr
end
```

This would change to C-W t or C-W b without going the 999 route. Im unsure if it would be worth though.

2021-06-29 04:35 UTC, aserowy commented on lua/tmux/navigate.lua
>  	if is_border(direction) then
for clarity we should refactor is_border into is_nvim_border. Thus, we can 

```lua
local function is_nvim_border(border)
	return winnr() == winnr("1" .. border)
end
[...]
if is_nvim_border(direction) and has_tmux_target(direction) then
    wrapper.change_pane(direction)
elseif is_nvim_border(direction) and cfg.options.navigation.cycle_navigation then
    wrap_window(direction)
else
    wincmd(direction)
end
```

This ensures the control flow is visible on the most upper scope.

2021-06-29 04:50 UTC, aserowy commented
Key descriptions are specified here <https://neovim.io/doc/user/windows.html>.

2021-06-29 18:26 UTC, jdsutherland commented
> Im starting to belive that we should use global functions. Thus we can inject and use key bindings like C-W t as wrapping functions. This would on the other hand break the current api... Hmm, but it would free us and would open us a lot more capabilities. Or is there a function in lua im not aware of to send keys to nvim within a lua function?
> 
> 
> local function wincmd_next(direction, count)
> 	local prev_winnr = winnr()
> 	wincmd(direction, count)
> 	return winnr() ~= prev_winnr
> end
> This would change to C-W t or C-W b without going the 999 route. Im unsure if it would be worth though.

I'm not sure I understand. This is my first time writing lua with neovim stuff btw, so I might not be very helpful. If you're tight on time and you'd rather just implement yourself, feel free, but I'm happy to try to assist.

2021-06-29 20:38 UTC, jdsutherland commented
The current changes have a problem:
![image](https://user-images.githubusercontent.com/5385846/123855967-63dd1900-d8d5-11eb-896e-316b948c0b60.png)

`(P1)` With the current PR changes https://github.com/aserowy/tmux.nvim/pull/8/files#diff-e28faf57259f9cb4b55c010e8244ac04e18dfe0b2fba5e277dfacc70d1aa9aa0L23-L25, pane 0 (nvim) with `cycle_navigation` set, `move_top` doesn't move to pane 2 (because `wrapper.has_neighbor()` is false). On the main branch, you've avoided this problem by returning true if cycle_navigation prior to checking `has_neighbor`:
https://github.com/aserowy/tmux.nvim/blob/df1bf1c337f7b60e0d49bfd354dfca7684e11299/lua/tmux/navigate.lua#L23-L25

But with the PR [adding a new conditional for nvim cycling](https://github.com/aserowy/tmux.nvim/pull/8/files#diff-e28faf57259f9cb4b55c010e8244ac04e18dfe0b2fba5e277dfacc70d1aa9aa0R53-R54), there are two problems:
1. `P1` results from removing https://github.com/aserowy/tmux.nvim/pull/8/files#diff-e28faf57259f9cb4b55c010e8244ac04e18dfe0b2fba5e277dfacc70d1aa9aa0L23-L25 
2. If you don't remove https://github.com/aserowy/tmux.nvim/pull/8/files#diff-e28faf57259f9cb4b55c010e8244ac04e18dfe0b2fba5e277dfacc70d1aa9aa0L23-L25, then `change_window_with_wrap()` will never occur because of `cycle_navigation = true` always returning true. So wrap around for vim windows cannot work this way.

I'll see if I can figure out a fix.

2021-06-29 20:50 UTC, jdsutherland commented
Alright, it's a bit more confusing now, but it works.

2021-07-02 05:33 UTC, aserowy commented
heho,

ty, i will check the pr tomorrow. <3

kind regards

2021-07-03 04:16 UTC, aserowy approved these changes

2021-07-03 04:18 UTC, aserowy commented
looks nice! thx for your help!

2021-07-03 04:21 UTC, aserowy commented
If your have time can you correct the formatting? (Otherwise ill press it through and correct it myself)
Just give me a ping pls :D

2021-07-03 14:29 UTC, jdsutherland commented
Just updated the formatting changes. (I assume you meant `stylua`).

2021-07-03 18:27 UTC, merged